name: match_incidents
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.0.0
  flutter_chat_types: ^3.0.0
  http: ^0.13.4
  uuid: ^3.0.6



  # Añadir las versiones compatibles de los paquetes de Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
