name: match_incidents
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  clipboard: ^0.1.2
  animated_text_kit: ^4.2.1
  flutter_chat_ui: 1.6.14
  flutter_chat_types: ^3.0.0
  http: ^1.2.1
  uuid: ^4.4.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  leak_tracker: ^10.0.4
  leak_tracker_flutter_testing: ^3.0.3
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  test_api: 0.7.0  # Ajustado a la versión que `flutter_test` necesita
  vm_service: 14.2.1  # Ajustado a la versión que `flutter_test` necesita
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.0.2
  google_sign_in_web: ^0.12.0
  flutter_signin_button: ^2.0.0
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
        - asset: fonts/Orbitron-Bold.ttf
          weight: 700
