// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8BzjWP60HEGVMDZ6Z5o_7tqEMQ9itI2Y',
    appId: '1:789241953207:web:8c185d5194cc1c383cc632',
    messagingSenderId: '789241953207',
    projectId: 'match-incidents-9e268',
    authDomain: 'match-incidents-9e268.firebaseapp.com',
    databaseURL: 'https://match-incidents-9e268-default-rtdb.firebaseio.com',
    storageBucket: 'match-incidents-9e268.appspot.com',
    measurementId: 'G-8KTTBVGT1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1710UQ9YyqejG-0E_qUd35_FD07hI-U',
    appId: '1:789241953207:android:d701d9616339f6273cc632',
    messagingSenderId: '789241953207',
    projectId: 'match-incidents-9e268',
    databaseURL: 'https://match-incidents-9e268-default-rtdb.firebaseio.com',
    storageBucket: 'match-incidents-9e268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5GQ7VqUYaS5RPeJxnpqEr2BymiF96Q8',
    appId: '1:789241953207:ios:69c3f978f67a19373cc632',
    messagingSenderId: '789241953207',
    projectId: 'match-incidents-9e268',
    databaseURL: 'https://match-incidents-9e268-default-rtdb.firebaseio.com',
    storageBucket: 'match-incidents-9e268.appspot.com',
    iosClientId: '789241953207-o5f6ebecr7b8cqs04gs2i4s2oollik4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchIncidents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5GQ7VqUYaS5RPeJxnpqEr2BymiF96Q8',
    appId: '1:789241953207:ios:69c3f978f67a19373cc632',
    messagingSenderId: '789241953207',
    projectId: 'match-incidents-9e268',
    databaseURL: 'https://match-incidents-9e268-default-rtdb.firebaseio.com',
    storageBucket: 'match-incidents-9e268.appspot.com',
    iosClientId: '789241953207-o5f6ebecr7b8cqs04gs2i4s2oollik4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchIncidents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8BzjWP60HEGVMDZ6Z5o_7tqEMQ9itI2Y',
    appId: '1:789241953207:web:6510e2d4d3878c943cc632',
    messagingSenderId: '789241953207',
    projectId: 'match-incidents-9e268',
    authDomain: 'match-incidents-9e268.firebaseapp.com',
    databaseURL: 'https://match-incidents-9e268-default-rtdb.firebaseio.com',
    storageBucket: 'match-incidents-9e268.appspot.com',
    measurementId: 'G-H2TEYH9H86',
  );
}
